name: UI and UD

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
      branches:
        -main
    pull_request:
      branches:
        -main
    # Allows you to run this workflow manually from the Actions tab
    # workflow_dispatch:
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6 # use the explicit version number
        with:
          build: npm run build
          start: npm start
  # deploy:
  #     runs-on: ubuntu-latest
  #     needs: cypress-run
  #     permissions:
  #         contents: write
  #         pages: write
  #         id-token: write
  #     environment:
  #       name: github-pages
  #       url: ${{steps.deployment.outputs.page_url}}
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v3
  #         with:
  #           token: ${{ secrets.GITHUB_TOKEN }}
  #       - name: use node.js
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: '18.x'
  #       - name: configure github pages
  #         uses: actions/configure-pages@v3
  #         with:
  #           static_site_generator: next
  #       - run: npm install
  #       - run: npm run build
  #       - name: upload artifacts
  #         uses: actions/upload-pages-artifact@v1
  #         with:
  #           path: "./out"
  #       - name: deploy
  #         id: deployment
  #         uses: actions/deploy-pages@v1
        
