name: CI and CD

on:
  push:
  pull_request:
    branches:
      - main
    # types:
    #   - opened
    #   - reopened
    #   - synchronize
    #   - closed

# concurrency: preview-${{ github.ref }}

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
  build:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/.'
  # deploy-preview:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pages: write
  #     id-token: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install and Build
  #       if: github.event.action != 'closed'
  #       run: |
  #         npm install
  #         npm run build
  #     - name: Deploy preview
  #       uses: rossjrw/pr-preview-action@v1
  #       with:
  #         source-dir: ./build/
  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Deploy
      uses: actions/deploy-pages@v4

        
